#ifndef __C_FEED_MODES
#define __C_FEED_MODES
#include <stdint.h>
#include "../NGC_RS274/_ngc_defines.h"

enum class e_feed_modes : uint16_t
{
	FEED_RATE_MINUTES_PER_UNIT_MODE = 93 * G_CODE_MULTIPLIER,
	FEED_RATE_UNITS_PER_MINUTE_MODE = 94 * G_CODE_MULTIPLIER,
	FEED_RATE_UNITS_PER_ROTATION = 95 * G_CODE_MULTIPLIER,
	FEED_RATE_CONSTANT_SURFACE_SPEED = 96 * G_CODE_MULTIPLIER,
	FEED_RATE_RPM_MODE = 97 * G_CODE_MULTIPLIER
};
#endif