#define __FRAMEWORK_COM_READ_TIMEOUT_MS 5000
#define __FRAMEWORK_INTRA_CPU_BAUD_RATE 250000
#define RING_BUFFER_SIZE 256

#define CPU_CLUSTER_COUNT 5

#define HEALTH_CHECK_TIME_MS 1000

#define CRC_BYTE_SIZE 2